### ISSUE TITLE
Plugin won't make API call if element is added on demand

### ISSUE THREAD

**Issue by franverona** [grimmdude/jquery-ajax-markup#1]
If I add an element on demand after page is initialized, this plugin won't make API call due to $.each usage when page is loaded.

You can see an example here:

https://jsfiddle.net/franverona/74a0kh8u/

It could be nice an option to execute API calls on demand: when adding an element, for lazy API calls loading, etc.

**Comment by grimmdude** [comment]
Good point. I don't think we can automatically watch the DOM for changes, but I could add a function to explicitly call this.  How would you expect this feature to be used; something like this?

``` javascript
var div = $('<div id="test" data-ajax-url="https://api.planetteamspeak.com/updatecheck/" data-ajax-type="json">Status: ~status~</div>');
$('body').append(div).ajaxMarkup();`
```

**Comment by franverona** [comment]
Yeah. I look for some kind of "event" about DOM changes, but I only found a Webkit solution not supported by IE (is called _Mutation Observer_):

http://stackoverflow.com/questions/16618876/determining-if-a-html-element-has-been-added-to-the-dom-dynamically

So yes, a function like that could be great.

**Comment by grimmdude** [comment]
OK, I'll work on a solution.  The main issue I want to avoid is requesting the same url again once it's already been loaded.

**Comment by franverona** [comment]
Thanks, but just to be clear I'm not demanding anything. I will look into this too. This is open source :+1: :smiley:

**Comment by grimmdude** [comment]
Check out that solution and see what you think.  Added `$.ajaxMarkup()` function with some options I outlined in the README.

**Comment by franverona** [comment]
Looks nice to me, but I think these lines:

```
if (options.container) {
    $ajaxMarkupElements = $(options.container).find('*[data-ajax-url]');
} else {
     $ajaxMarkupElements = $('*[data-ajax-url]');
}
```

https://github.com/grimmdude/jquery-ajax-markup/blob/master/jquery-ajax-markup.js#L31

Should be changed as follows:

```
if (options.container) {
    $ajaxMarkupElements = $(options.container);
} else {
     $ajaxMarkupElements = $('*[data-ajax-url]');
}
```

In my case, I was expecting this plugin behaviour:

```
<div id="test" data-ajax-url="https://api.domain.com/function/" data-ajax-type="json">
  ~result~
</div>
$.ajaxMarkup({container: '#test'});
```

And plugin forced me to an HTML markup like this:

```
<div id="test">
  <div data-ajax-url="https://api.domain.com/function/" data-ajax-type="json">
    ~result~
  </div>
</div>
$.ajaxMarkup({container: '#test'});
```

**Comment by grimmdude** [comment]
Hey,

I see your point, I think it's nice to have a `container` option for some scenarios instead of specifying each individual element though.  I've made a change so it can work like this:

``` js
<div id="test" data-ajax-url="https://api.domain.com/function/" data-ajax-type="json">
  ~result~
</div>

$('#test').ajaxMarkup();
```

Optionally you could write it like this:

``` js
<div id="container">
    <div data-ajax-url="https://api.domain.com/function/" data-ajax-type="json">
       ~result~
   </div>
    <div data-ajax-url="https://api.domain.com/function/" data-ajax-type="json">
       ~result~
   </div>
</div>

$('#container').ajaxMarkup({container: true});
```

I think this should solve the problem.

**Comment by franverona** [comment]
Absolutely. I think I misunderstood **container** option in first place.

Thanks!

**Comment by grimmdude** [comment]
Cool, thanks for your input!
