### ISSUE TITLE
Suggestion: improve variable replacement instead of clearing div

### ISSUE THREAD

**Issue by franverona** [grimmdude/jquery-ajax-markup#2]
When an API call return a json, in some cases it returns more info than just one field. For instance, I make an API call to **/api/user/:userId** and server gives me name, email and avatar url.

As a suggestion, it would be nice to improve replacement so div won't be cleared. Instead, plugin will read div contents and replace ~field~ with its related field.

This solution is even more accurate to a "template" behaviour.

You can see what I'm talking in this snippet: https://jsfiddle.net/franverona/rtdzfp7p/

In my demo, to keep dom structure I had to call the API twice.

**Comment by grimmdude** [comment]
I'm having some trouble understanding your issue.  I updated your jsfiddle with the changes we made in #1.  Do those changes fix this issue?  If not could you could you clarify a bit?  Thanks,

-Garrett

**Comment by franverona** [comment]
Of course you didn't understand me. I didn't update my jsfiddle, so you were seeing an old version :sob:  (my bad).

Here it is: https://jsfiddle.net/franverona/rtdzfp7p/3/ :+1: 

Summarizing: after API call is complete, ajaxMarkup doesn't keep DOM structure. Instead, plugin replace current div content with only text + fields populated. It could be more useful if it remains DOM structure and only replace fields instead of replacing whole div content.

More like a template instead of a "hard replacer".

**Comment by grimmdude** [comment]
Ah, ok got it.  This issue should now be fixed with the latest commit.

Also, note that if you do happen to use the same url twice in the markup this plugin will only call it once so there shouldn't be an issue with duplicate requests.

-Garrett
