### ISSUE TITLE
Plain text does not get replaced

### ISSUE THREAD

**Issue by cideveloper** [grimmdude/jquery-ajax-markup#3]
If I have an element that has placeholder text within it and the data-ajax-url returns plaint text, there is no replacement done. Original text stays in element.

Element

``` html
<p data-ajax-url="index.php?type=text">Running....</p>
```

AJAX Response

``` html
Hello World
```

Current Result

``` html
<p data-ajax-url="index.php?type=text">Running....</p>
```

Result should be

``` html
<p data-ajax-url="index.php?type=text">Hello World</p>
```

Are you taking pull requests for fixes?

**Comment by franverona** [comment]
I think that you have to specify your API call content type result. For example:

`<p data-ajax-url="index.php?type=text" data-ajax-type="html">Running....</p>`

**Comment by grimmdude** [comment]
I found a bug and have fixed in my last commit.  As @franverona stated, be sure to specify `data-ajax-type="html"`.  Also, PRs are welcome!

-G
